### ISSUE TITLE
Kanji for Japanese?

### ISSUE THREAD

**Issue by ravener** [jyaif/ppl-i18n#240]
May I ask why the Japanese translation uses all katakana and never any kanji.

I may try contributing to the Japanese translation a bit so asking if this is some design decision or a font issue not allowing kanji characters?

Kanji can also shorten the words, e.g a 6 letter katakana word can just be a 2 character kanji.

If there's no objections I'd like to also start adding some kanji to make it more readable.

**Comment by jyaif** [comment]
You can use kanjis. The downside each new kanji will make the binary a little bit bigger, but that's not a big deal.

One thing to keep in mind is that PewPew Live is rendering everything using lines, even text. So it's possible that complex kanjis may not be very readable.

Here's an example of Mandarin, to give you an idea of what kanjis would look like:
![chinese](https://user-images.githubusercontent.com/251239/165912455-eecc2124-bf63-4a2e-be50-adcd2f58bf68.png)

And finally, thanks a lot for offering to take this on :-)

**Comment by ravener** [comment]
Sounds good, thanks. About the size though I believe a good amount of the characters will be shared by the Chinese translations so it probably won't be much.

I'll see what I can do

**Comment by ravener** [comment]
Since I already started working on this, I think I'll close this issue now.
