### ISSUE TITLE
Adding Ukrainian language

### ISSUE THREAD

**Issue by Quarlify** [jyaif/ppl-i18n#36]
Wanna make Ukrainian translation

**Comment by SKPG-Tech** [comment]
Yeah I think you can, we need to wait for JF to accept this.

**Comment by SKPG-Tech** [comment]
@Quarlify Great news, you can translate the Game to Ukrainian. JF will add the files you need to edit, please wait. If you need help join the discord server. https://discord.com/invite/kpkPgDG

**Comment by jyaif** [comment]
Hi!
Yes, Ukrainian translation would be great!
I added the file for Ukrainian ( ukr.po ), so you can start translating if you want.

**Comment by SKPG-Tech** [comment]
If you have any question/need help ask them in the discord server, I'm closing this issue
